In [ ]:
x = y =z = "pen"
print(x)
print(y)
print(z)

In [ ]:
a = 78
b=887
print(a+b)

In [ ]:
x = str("11")
y = str(2)
z = str(10.20)
print(x)
print(y)
print(z)  

In [ ]:
  
x = 2
y = 44
z = 48
 
print(x+y)
print(x*y)
print(x-y)

print

In [ ]:
for i in range (2,11,3): 
    print(i)

In [ ]:
for i in range(1,50,2):
    print(i)

In [ ]:
fruits = ["Apple","banana","cherry"]
for fruit in fruits :
    print(fruit.upper())
for idx, fruit in enumerate(fruits, start=1):
        print(f"{idx} {fruit}")

In [ ]:
for num in range(10):
if num == 5:
    break
print(num, end= " ")
print() 
for num in range(10):
    if num % 2 == 0:
        continue
    print(num, end=" ")

In [ ]:
for num in range(10):
    if num % 2 == 0:
        continue
    print(num, end=" ")

In [ ]:
for i in range(1,4):
  for j in range (1,4):
    print(f"{i+j:3}",end=" ") 
  print()


In [ ]:
num = int(input("Enter a number:"))
fact = 1

while num > 0:
    fact *= num
    num -= 1

print(fact)


In [ ]:
sentence = input("enter a sentence:")
vowels = []
for ch in sentence:
    if ch.lower() in "aeiou":
        vowels.append(ch)
print(vowels)

In [ ]:
def min_max(numbers):
    return min(numbers), max(numbers)
low, high = min_max({4,10,7,6,1})
print(f"min: {low}, max: {high}")

In [ ]:

rows = int(input("Enter the number of rows: "))

for i in range(1, rows + 1):
    for j in range(i):
        print("*", end=" ")
    print()


In [ ]:

        list = []
        list.append("hamja")
        list.append("ali")
        list.append("mazari")
        print(list)
        with open("batch.txt","w") as file:
            for item in list:
                file.write(item + "\n")

        print("successful")
        with open("demo.txt","r") as file:
            content = file.readlines()

In [ ]:
rows = 1
while rows<= 5:
    col = 1
    while col<= rows:
        print("*",end=" ")
        col+=1
print()
rows += 1


In [ ]:
arr = np.arange(10)
print("array:",arr)
print("memmory size in bytes:",arr.nbytes)


In [ ]:
import as numpy np
arr = np.arange(1,17).reshape(4,4)
print("array:\n",arr)
first_row = arr[3,:]
print("first Row:", first_row)
last_col = arr[:,2]
print("last column:", last_col)

In [ ]:
df_clean["year"] = df_clean["ivoiceDate"].dt.year
df_clean["month"] = df_clean["invoiceDate"].dt.monthx
      print("StEP 4: Date features added")
print(df_clean[["invoiceDate","Year","month","DayofWeek","Hour"]].head(10))
print("\n")

In [ ]:
customer_summary =df_clean.groupby("customerID").agg(
    TotalSpent=("TotalPrice","sum"),
    Numorders=("invoiceno","nunique"),
    AvgorderValue=("TotalPrice","mean")
    LastPurchase=("InvoiceDate","max")
).sort_value("Total Spent")

In [ ]:
!pip install numpy


In [ ]:
pip install --upgrade pip

In [ ]:
!pip install pandas

In [ ]:

!pip install seaborn




In [ ]:
!pip install numpy


In [5]:
import numpy as np

# Create sample data
arr = np.array([10, 20, 30, 40, 50])

print("Original Array:")
print(arr)

# Basic Operations
print("\nAddition (+5):")
print(arr + 5)

print("\nSubtraction (-5):")
print(arr - 5)

print("\nMultiplication (*2):")
print(arr * 2)

print("\nDivision (/2):")
print(arr / 2)

# Statistical Operations
print("\nSum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("Standard Deviation:", np.std(arr))

# Reshaping
arr2 = arr.reshape(5, 1)
print("\nReshaped Array (5x1):")
print(arr2)

# Indexing and Slicing
print("\nFirst Element:", arr[0])
print("Last Element:", arr[-1])
print("Elements from index 1 to 3:", arr[1:4])

# Create another array
arr3 = np.array([1, 2, 3, 4, 5])

# Element-wise Operations
print("\nElement-wise Addition:")
print(arr + arr3)

print("\nElement-wise Multiplication:")
print(arr * arr3)

# Matrix Operations
matrix = np.array([[1, 2], [3, 4]])

print("\nMatrix:")
print(matrix)

print("\nTranspose:")
print(matrix.T)

print("\nDeterminant:")
print(np.linalg.det(matrix))

print("\nInverse:")
print(np.linalg.inv(matrix))


Original Array:
[10 20 30 40 50]

Addition (+5):
[15 25 35 45 55]

Subtraction (-5):
[ 5 15 25 35 45]

Multiplication (*2):
[ 20  40  60  80 100]

Division (/2):
[ 5. 10. 15. 20. 25.]

Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10
Standard Deviation: 14.142135623730951

Reshaped Array (5x1):
[[10]
 [20]
 [30]
 [40]
 [50]]

First Element: 10
Last Element: 50
Elements from index 1 to 3: [20 30 40]

Element-wise Addition:
[11 22 33 44 55]

Element-wise Multiplication:
[ 10  40  90 160 250]

Matrix:
[[1 2]
 [3 4]]

Transpose:
[[1 3]
 [2 4]]

Determinant:
-2.0000000000000004

Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [6]:
import numpy as np

# Sample data
data = np.array([12, 18, 25, 30, 45, 50, 60, 72, 85, 90])

print("Data:", data)

# 1. Sum
print("Sum:", np.sum(data))

# 2. Mean (Average)
print("Mean:", np.mean(data))

# 3. Median
print("Median:", np.median(data))

# 4. Standard Deviation
print("Standard Deviation:", np.std(data))

# 5. Variance
print("Variance:", np.var(data))

# 6. Maximum
print("Maximum:", np.max(data))

# 7. Minimum
print("Minimum:", np.min(data))

# 8. Range
print("Range:", np.ptp(data))   # Max - Min

# 9. Percentiles
print("25th Percentile:", np.percentile(data, 25))
print("50th Percentile:", np.percentile(data, 50))
print("75th Percentile:", np.percentile(data, 75))

# 10. Cumulative Sum
print("Cumulative Sum:", np.cumsum(data))

# 11. Product of Elements
print("Product:", np.prod(data))

# 12. Index of Maximum and Minimum
print("Index of Maximum:", np.argmax(data))
print("Index of Minimum:", np.argmin(data))

# 13. Unique Values
print("Unique Values:", np.unique(data))

Data: [12 18 25 30 45 50 60 72 85 90]
Sum: 487
Mean: 48.7
Median: 47.5
Standard Deviation: 26.287069064465896
Variance: 691.01
Maximum: 90
Minimum: 12
Range: 78
25th Percentile: 26.25
50th Percentile: 47.5
75th Percentile: 69.0
Cumulative Sum: [ 12  30  55  85 130 180 240 312 397 487]
Product: 12045996000000000
Index of Maximum: 9
Index of Minimum: 0
Unique Values: [12 18 25 30 45 50 60 72 85 90]


In [7]:
import numpy as np

# 3x3 Matrix
matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

print("Matrix:\n", matrix)

# Row-wise Sum
print("\nRow-wise Sum:", np.sum(matrix, axis=1))

# Column-wise Sum
print("Column-wise Sum:", np.sum(matrix, axis=0))

# Row-wise Mean
print("Row-wise Mean:", np.mean(matrix, axis=1))

# Column-wise Mean
print("Column-wise Mean:", np.mean(matrix, axis=0))

# Maximum in each Row
print("Row-wise Maximum:", np.max(matrix, axis=1))

# Minimum in each Column
print("Column-wise Minimum:", np.min(matrix, axis=0))

Matrix:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Row-wise Sum: [ 60 150 240]
Column-wise Sum: [120 150 180]
Row-wise Mean: [20. 50. 80.]
Column-wise Mean: [40. 50. 60.]
Row-wise Maximum: [30 60 90]
Column-wise Minimum: [10 20 30]


In [8]:
import sys
print(sys.executable)

c:\Users\Shivam Mishra\AppData\Local\Programs\Python\Python313\python.exe


In [ ]:
!where python

In [9]:
!python -m pip show numpy

Name: numpy
Version: 2.5.1
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License-Expression: BSD-3-Clause AND 0BSD AND MIT AND Zlib AND CC0-1.0
Location: c:\Users\Shivam Mishra\AppData\Local\Programs\Python\Python313\Lib\site-packages
Requires: 
Required-by: contourpy, matplotlib, pandas, seaborn


In [10]:
import sys
!{sys.executable} -m pip install numpy

'c:\Users\Shivam' is not recognized as an internal or external command,
operable program or batch file.


In [ ]:
import sys
print(sys.executable)

In [ ]:
import sys
print(sys.executable)

In [ ]:
import sys
!"{sys.executable}" -m pip install numpy

In [ ]:
import numpy as np
print(np.__version__)

In [11]:
import pandas as pd

# Sample data
data = [12, 18, 25, 30, 45, 50, 60, 72, 85, 90]

# Create a DataFrame
df = pd.DataFrame(data, columns=["Marks"])

print("DataFrame:")
print(df)

# 1. Sum
print("\nSum:")
print(df["Marks"].sum())

# 2. Mean
print("\nMean:")
print(df["Marks"].mean())

# 3. Median
print("\nMedian:")
print(df["Marks"].median())

# 4. Standard Deviation
print("\nStandard Deviation:")
print(df["Marks"].std())

# 5. Variance
print("\nVariance:")
print(df["Marks"].var())

# 6. Maximum
print("\nMaximum:")
print(df["Marks"].max())

# 7. Minimum
print("\nMinimum:")
print(df["Marks"].min())

# 8. Count
print("\nCount:")
print(df["Marks"].count())

# 9. Describe (Complete Statistical Summary)
print("\nStatistical Summary:")
print(df.describe())

# 10. Cumulative Sum
print("\nCumulative Sum:")
print(df["Marks"].cumsum())

# 11. Unique Values
print("\nUnique Values:")
print(df["Marks"].unique())

# 12. Value Counts
print("\nValue Counts:")
print(df["Marks"].value_counts())

# 13. Largest and Smallest Values
print("\nTop 3 Largest Values:")
print(df["Marks"].nlargest(3))

print("\nTop 3 Smallest Values:")
print(df["Marks"].nsmallest(3))

DataFrame:
   Marks
0     12
1     18
2     25
3     30
4     45
5     50
6     60
7     72
8     85
9     90

Sum:
487

Mean:
48.7

Median:
47.5

Standard Deviation:
27.709003751287934

Variance:
767.7888888888888

Maximum:
90

Minimum:
12

Count:
10

Statistical Summary:
           Marks
count  10.000000
mean   48.700000
std    27.709004
min    12.000000
25%    26.250000
50%    47.500000
75%    69.000000
max    90.000000

Cumulative Sum:
0     12
1     30
2     55
3     85
4    130
5    180
6    240
7    312
8    397
9    487
Name: Marks, dtype: int64

Unique Values:
[12 18 25 30 45 50 60 72 85 90]

Value Counts:
Marks
12    1
18    1
25    1
30    1
45    1
50    1
60    1
72    1
85    1
90    1
Name: count, dtype: int64

Top 3 Largest Values:
9    90
8    85
7    72
Name: Marks, dtype: int64

Top 3 Smallest Values:
0    12
1    18
2    25
Name: Marks, dtype: int64


In [ ]:
import sys
!"{sys.executable}" -m pip install seaborn

In [13]:
import pandas as pd

# Sample Data
data = {
    "Name": ["A", "B", "C", "D", "E"],
    "Math": [85, 78, 92, 70, 88],
    "Science": [90, 75, 95, 72, 85],
    "English": [80, 82, 91, 68, 87]
}

df = pd.DataFrame(data)

print(df)

# Statistical Summary
print("\nSummary:")
print(df.describe())

# Mean of each subject
print("\nAverage Marks:")
print(df.mean(numeric_only=True))

# Maximum marks
print("\nMaximum Marks:")
print(df.max(numeric_only=True))

# Minimum marks
print("\nMinimum Marks:")
print(df.min(numeric_only=True))

# Correlation
print("\nCorrelation Matrix:")
print(df.corr(numeric_only=True))

  Name  Math  Science  English
0    A    85       90       80
1    B    78       75       82
2    C    92       95       91
3    D    70       72       68
4    E    88       85       87

Summary:
           Math    Science    English
count   5.00000   5.000000   5.000000
mean   82.60000  83.400000  81.600000
std     8.70632   9.762172   8.734987
min    70.00000  72.000000  68.000000
25%    78.00000  75.000000  80.000000
50%    85.00000  85.000000  82.000000
75%    88.00000  90.000000  87.000000
max    92.00000  95.000000  91.000000

Average Marks:
Math       82.6
Science    83.4
English    81.6
dtype: float64

Maximum Marks:
Math       92
Science    95
English    91
dtype: int64

Minimum Marks:
Math       70
Science    72
English    68
dtype: int64

Correlation Matrix:
             Math   Science   English
Math     1.000000  0.928905  0.930971
Science  0.928905  1.000000  0.758745
English  0.930971  0.758745  1.000000


In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Sample Data
data = {
    "Student": ["A", "B", "C", "D", "E"],
    "Math": [85, 78, 92, 70, 88],
    "Science": [90, 75, 95, 72, 85],
    "English": [80, 82, 91, 68, 87]
}

df = pd.DataFrame(data)

In [ ]:
sns.scatterplot(x="Math", y="Science", data=df)
plt.title("Scatter Plot")
plt.show()

In [ ]:
sns.lineplot(x="Student", y="Math", data=df)
plt.title("Line Plot")
plt.show()

In [ ]:
sns.barplot(x="Student", y="Math", data=df)
plt.title("Bar Plot")
plt.show()

In [ ]:
sns.histplot(df["Math"], bins=5)
plt.title("Histogram")
plt.show()

In [ ]:
sns.boxplot(y="Math", data=df)
plt.title("Box Plot")
plt.show()

In [ ]:
sns.violinplot(y="Math", data=df)
plt.title("Violin Plot")
plt.show()

In [ ]:
data = pd.DataFrame({
    "Grade": ["A", "B", "A", "C", "B", "A", "C", "A"]
})

sns.countplot(x="Grade", data=data)
plt.title("Count Plot")
plt.show()

In [ ]:
corr = df.drop("Student", axis=1).corr()

sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("Heatmap")
plt.show()

In [ ]:
sns.pairplot(df.drop("Student", axis=1))
plt.show()

In [ ]:
sns.kdeplot(df["Math"], fill=True)
plt.title("KDE Plot")
plt.show()

In [ ]:
sns.jointplot(x="Math", y="Science", data=df, kind="scatter")
plt.show()

In [ ]:
sns.rugplot(df["Math"])
plt.title("Rug Plot")
plt.show()

In [ ]:
sns.stripplot(y="Math", data=df)
plt.title("Strip Plot")
plt.show()

In [ ]:
sns.swarmplot(y="Math", data=df)
plt.title("Swarm Plot")
plt.show()

In [ ]:
sns.regplot(x="Math", y="Science", data=df)
plt.title("Regression Plot")
plt.show()

In [ ]:
sns.catplot(x="Student", y="Math", kind="bar", data=df)
plt.show()

In [1]:
sns.ecdfplot(df["Math"])
plt.title("ECDF Plot")
plt.show()

NameError: name 'sns' is not defined

In [3]:
sns.displot(df["Math"], kde=True)
plt.show()

NameError: name 'sns' is not defined

In [2]:
sns.relplot(x="Math", y="Science", data=df)
plt.show()

NameError: name 'sns' is not defined

In [1]:
sns.lmplot(x="Math", y="Science", data=df)
plt.show()

NameError: name 'sns' is not defined